# bug faced on python:3-alpine
# myodbc-installer always not found when excute
# this container based on ubuntu and  will changed to alpine based if bug fixed.

FROM python:3
MAINTAINER Jack King

WORKDIR /usr/src/app

# install requirements
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pymemcache

# install pyodbc
RUN apt-get update && apt-get install -y unixodbc python-pyodbc && \
    rm -rf /var/lib/apt/lists/*

# install mysql odbc driver
ARG MYSQL_DRIVER_FILENAME='mysql-connector-odbc-8.0.11-linux-glibc2.12-x86-64bit.tar.gz'
RUN cd /tmp && \
    wget https://cdn.mysql.com//Downloads/Connector-ODBC/8.0/$MYSQL_DRIVER_FILENAME && \
    tar xzvf $MYSQL_DRIVER_FILENAME && cd mysql-connector-odbc-8.0.11-linux-glibc2.12-x86-64bit && \
    cp bin/* /usr/local/bin && \
    cp lib/* /usr/local/lib && \
    myodbc-installer -a -d -n "MySQL ODBC 8.0 Driver" -t "Driver=/usr/local/lib/libmyodbc8w.so" && \
    myodbc-installer -a -d -n "MySQL ODBC 8.0" -t "Driver=/usr/local/lib/libmyodbc8a.so" && \
    myodbc-installer -d -l

# copy code to work folder
COPY . .

# set env
ENV LISTENING_ADDRESS='0.0.0.0'


# entry
CMD python start.py